-- Migration script for persona_roles

-- 1. Create the persona_roles table
CREATE TABLE IF NOT EXISTS persona_roles (
    id INT NOT NULL AUTO_INCREMENT,
    persona_id INT NOT NULL,
    tipo_persona_id INT NOT NULL,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_asignacion TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_persona_rol (persona_id, tipo_persona_id),

    CONSTRAINT fk_pr_persona FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    CONSTRAINT fk_pr_tipo FOREIGN KEY (tipo_persona_id) REFERENCES tipos_persona(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Migrate existing roles from personas table
INSERT IGNORE INTO persona_roles (persona_id, tipo_persona_id)
SELECT id, tipo_persona_id
FROM personas
WHERE tipo_persona_id IS NOT NULL;

-- 3. Drop tipo_persona_id from personas table
-- First, drop the foreign key if it exists
SET @exist_fk := (SELECT count(*) FROM information_schema.table_constraints WHERE table_name = 'personas' AND constraint_name = 'fk_personas_tipo' AND constraint_schema = DATABASE());
SET @sql_drop_fk := if(@exist_fk > 0, 'ALTER TABLE personas DROP FOREIGN KEY fk_personas_tipo', 'SELECT 1');
PREPARE stmt FROM @sql_drop_fk;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Also try to drop default foreign key generated by mysql if named differently (like personas_ibfk_X)
SET @fk_name := (SELECT CONSTRAINT_NAME FROM information_schema.key_column_usage WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'personas' AND COLUMN_NAME = 'tipo_persona_id' AND REFERENCED_TABLE_NAME IS NOT NULL LIMIT 1);
SET @sql_drop_fk_auto := IF(@fk_name IS NOT NULL, CONCAT('ALTER TABLE personas DROP FOREIGN KEY ', @fk_name), 'SELECT 1');
PREPARE stmt_auto FROM @sql_drop_fk_auto;
EXECUTE stmt_auto;
DEALLOCATE PREPARE stmt_auto;

-- Drop the column
SET @exist_col := (SELECT count(*) FROM information_schema.columns WHERE table_name = 'personas' AND column_name = 'tipo_persona_id' AND table_schema = DATABASE());
SET @sql_drop_col := if(@exist_col > 0, 'ALTER TABLE personas DROP COLUMN tipo_persona_id', 'SELECT 1');
PREPARE stmt FROM @sql_drop_col;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
